****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
* Date:                 Tue May 23 10:22:50 CEST 2023
* Job name:             run_py.sh
* Job id:               30347190
* User:                 namourou
* Account:              lsst
* Submit host:          cca004
* Partition:            htc
* Quality of service:   normal
* Nodelist:             ccwslurm0321
****************************************************************
DESC setup
GO1
charged: amico_cosmoDC2 p_matching _sn5
Matching Initialisation
Using matching : p_matching
Opening catalogs :  amico_cosmoDC2
cut is : p_matching
AMICO CosmoDC2 matching
Traceback (most recent call last):
  File "/pbs/home/n/namourou/test_jupyter/cluster_challenge/matching/clevar_matching.py", line 57, in <module>
    c1 = ClCatalog.read(amico_path + 'Catalog' + cut1 + '.fits', 'c1', full = True)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/clevar/clevar/catalog.py", line 1047, in read
    data = ClData.read(filename)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/clevar/clevar/catalog.py", line 103, in read
    return ClData(APtable.read(*args, **kwargs))
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/io/registry/core.py", line 197, in read
    fileobj = ctx.__enter__()
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_i/cuts/Catalogp_matching.fits'
G02
GO3
****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
Date: Tue May 23 10:22:55 CEST 2023
Job informations can be found using these commands:
Accounting:
sacct -j 30347190
Efficiency:
seff 30347190
****************************************************************
