****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
* Date:                 Tue Apr 25 16:42:00 CEST 2023
* Job name:             run_py.sh
* Job id:               27322253
* User:                 namourou
* Account:              lsst
* Submit host:          cca004
* Partition:            htc
* Quality of service:   normal
* Nodelist:             ccwslurm0321
****************************************************************
DESC setup
GO1
Merging amico files
Reading files at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_y/ which will be saved at /sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_y/
Traceback (most recent call last):
  File "/pbs/home/n/namourou/test_jupyter/cluster_challenge/prepare_catalogs/merge_amico_mb.py", line 22, in <module>
    large_amico_data = Table.read(inpath + tiles[0] + 'map_associations.fits') 
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/io/registry/core.py", line 197, in read
    fileobj = ctx.__enter__()
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_y/10066map_associations.fits'
G02
Reading AMICO files
['ID', 'Xphys', 'Yphys', 'Zphys', 'LAMBSTAR', 'SN_NO_CLUSTER', 'SN', 'UID', 'TILE']
Number of AMICO clusters =  165149
Traceback (most recent call last):
  File "/pbs/home/n/namourou/test_jupyter/cluster_challenge/prepare_catalogs/read_amico.py", line 46, in <module>
    mb_amico_data = Table.read(mb_inpath)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/table/connect.py", line 62, in __call__
    out = self.registry.read(cls, *args, **kwargs)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/io/registry/core.py", line 197, in read
    fileobj = ctx.__enter__()
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/sps/lsst/users/namourou/conda_clone_210223/descv1.1/lib/python3.10/site-packages/astropy/utils/data.py", line 271, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/sps/lsst/groups/clusters/amico_validation_project/catalogs/AMICO/amico_cats/amico_map_associations_flxzb_mag/mag_y/all_maps.fits'
GO3
****************************************************************
*                      SLURM Batch System                      *
*           IN2P3 Computing Centre, Villeurbanne FR            *
****************************************************************
Date: Tue Apr 25 16:42:20 CEST 2023
Job informations can be found using these commands:
Accounting:
sacct -j 27322253
Efficiency:
seff 27322253
****************************************************************
